name: IssueTempForm
description: Report a bug or issue with the repository
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - ArsiaC01

body:
  - type: markdown
    id: issuedetails
    attributes:
      value: "## Issue Details"
  - type: textarea
    id: explainissue
    attributes:
      label: Explain your issue
      description: Please include what the experienced and expected behavior is. *Be precise in your description and give as much detail as possible.*
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: markdown
    id: environmentdetails
    attributes:
      value: "## Environment Details"
  - type: dropdown
    id: version
    attributes:
      label: Software Version
      description: What version of the program are you running? *Please ensure you have updated to the latest release `v1.2.3` in case your problem has already been fixed.*
      options:
        - 1.2.3 (Latest Supported)
        - 1.3.0 (Bleeding Edge)
    validations:
      required: true
  - type: checkboxes
    id: isSchoolComputer
    attributes:
      label: School Computer
      options:
        - label: Check box if this is a school computer / computer with restricted permissions.
          required: false
  
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
