name: .NET TestWorkflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    # Sets a custom name for the builds for each job configuration.
    name: Build for ${{ matrix.os }}
    
    #Creates a build matrix which allows for multiple job configurations with the same steps.
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.*
        
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build Program
      run: dotnet build --no-restore
      
    - name: Test Built Program
      run: dotnet test --no-build --verbosity normal
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        # Artifact name
        name: GH-Actions-Art-Test for ${{ matrix.os }}
        # A file, directory or wildcard pattern that describes what to upload
        path: GH-Actions-Art-Test/bin/debug/net6.0
