name: .NET TestWorkflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.*
        
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build Program
      run: dotnet build --no-restore
      
    - name: Test Built Program
      run: dotnet test --no-build --verbosity normal
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        # Artifact name
        name: TestResults
        # A file, directory or wildcard pattern that describes what to upload
        path: GH-Actions-Art-Test
